{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Accessibility to Public Services: Ecuador Case"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import geopandas as gpd #Para archivos .shp \n",
    "import matplotlib.pyplot as plt #Para gráficar \n",
    "#Se define el tamaño de salidad de las gráficas\n",
    "\n",
    "import numpy as np \n",
    "import pandas as pd\n",
    "\n",
    "from shapely import wkt\n",
    "import geopy.distance\n",
    "from math import radians, cos, sin, asin, sqrt\n",
    "\n",
    "from pandas.core.frame import DataFrame\n",
    "from functools import reduce\n",
    "import pyproj as pp\n",
    "from pyproj import Proj"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Personas pobres lejos de los centros de anteción"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>zp</th>\n",
       "      <th>ud_mies</th>\n",
       "      <th>dpa_provin</th>\n",
       "      <th>dpa_despro</th>\n",
       "      <th>dpa_cant</th>\n",
       "      <th>dpa_descan</th>\n",
       "      <th>dpa_parroq</th>\n",
       "      <th>dpa_despar</th>\n",
       "      <th>beneficio</th>\n",
       "      <th>edad</th>\n",
       "      <th>lat</th>\n",
       "      <th>lon</th>\n",
       "      <th>corte</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Zona Planificación 6</td>\n",
       "      <td>UNIDAD DESCONCENTRADA ZONAL 6</td>\n",
       "      <td>1</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>108</td>\n",
       "      <td>SANTA ISABEL</td>\n",
       "      <td>10851</td>\n",
       "      <td>ABDON CALDERON (LA UNION)</td>\n",
       "      <td>PENSION MIS MEJORES AÑOS</td>\n",
       "      <td>73.0</td>\n",
       "      <td>-3.200741</td>\n",
       "      <td>-79.293510</td>\n",
       "      <td>julio_2022</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Zona Planificación 6</td>\n",
       "      <td>UNIDAD DESCONCENTRADA ZONAL 6</td>\n",
       "      <td>1</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>101</td>\n",
       "      <td>CUENCA</td>\n",
       "      <td>10150</td>\n",
       "      <td>CUENCA</td>\n",
       "      <td>PENSION PARA ADULTOS MAYORES</td>\n",
       "      <td>81.0</td>\n",
       "      <td>-2.888826</td>\n",
       "      <td>-79.043392</td>\n",
       "      <td>julio_2022</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                     zp                        ud_mies dpa_provin dpa_despro  \\\n",
       "0  Zona Planificación 6  UNIDAD DESCONCENTRADA ZONAL 6          1      AZUAY   \n",
       "1  Zona Planificación 6  UNIDAD DESCONCENTRADA ZONAL 6          1      AZUAY   \n",
       "\n",
       "   dpa_cant    dpa_descan  dpa_parroq                 dpa_despar  \\\n",
       "0       108  SANTA ISABEL       10851  ABDON CALDERON (LA UNION)   \n",
       "1       101        CUENCA       10150                     CUENCA   \n",
       "\n",
       "                      beneficio  edad       lat        lon       corte  \n",
       "0      PENSION MIS MEJORES AÑOS  73.0 -3.200741 -79.293510  julio_2022  \n",
       "1  PENSION PARA ADULTOS MAYORES  81.0 -2.888826 -79.043392  julio_2022  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Database from MIES\n",
    "\n",
    "# BDH and others pensions \n",
    "df_1 = pd.read_excel(\"https://info.inclusion.gob.ec/images/usuarios_externos/2022/BENEFICIARIOS_BONOS_PENSIONES_JUL2022.xls\", sheet_name= \"PARTE 1 JULIO2022\",dtype={'dpa_provin': str})\n",
    "df_2 = pd.read_excel(\"https://info.inclusion.gob.ec/images/usuarios_externos/2022/BENEFICIARIOS_BONOS_PENSIONES_JUL2022.xls\", sheet_name= \"PARTE 2 JULIO2022\")\n",
    "df_MIES = pd.concat([df_1, df_2], ignore_index=True)\n",
    "df_MIES.head(2)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<AxesSubplot:>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAQgAAAD4CAYAAAAQE3hSAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAMrElEQVR4nO3dfazd9V3A8feHS8e6KQJyi6WUlcyuGRsbzW54yEyW8DyXjerCXLO5JpIRE02YMSRUiDidBoNZzIKJYc7YBcKCGZYqKtZmZBkpZbfC1jVYocr6QIVO0gyWykP9+Mf93XLozof7cB5+517er+TmnPP9/c45nzTw7u+c37mnkZlIUjcntT2ApNFlICSVDISkkoGQVDIQkkonD/PJzjzzzFy1atUwn1LSDHbu3PmjzBzvtm2ogVi1ahWTk5PDfEpJM4iIH1bbfIkhqWQgJJUMhKSSgZBUMhCSSkM9izGTWzfv4t4d+zmWyVgE6y9eyZfWXdD2WNJb1sgE4tbNu7j70X3Hbx/LPH7bSEjtGJmXGPfu2D+ndUmDNzKBOFZ8L0W1LmnwRiYQYxFzWpc0eCMTiPUXr5zTuqTBG5k3KaffiPQshjQ6YpjfSTkxMZH+spY0WiJiZ2ZOdNs2Mi8xJI0eAyGpZCAklQyEpJKBkFQyEJJKBkJSyUBIKhkISSUDIalkICSVDISkkoGQVDIQkkoGQlLJQEgqGQhJJQMhqWQgJJUMhKSSgZBUMhCSSgZCUslASCoZCEklAyGpZCAklQyEpNKMgYiIt0fEYxHxvYjYHRFfbNbPiIitEfFUc3n64MeVNEyzOYJ4GbgsMz8IXAhcExGXADcD2zJzNbCtuS1pEZkxEDnlpebmkuYngWuBTc36JmDdIAaU1J5ZvQcREWMR8QTwPLA1M3cAZ2XmIYDmcllx3xsiYjIiJg8fPtynsSUNw6wCkZnHMvNC4Bzgooh4/2yfIDPvysyJzJwYHx+f55iS2jCnsxiZeQR4GLgGeC4ilgM0l8/3ezhJ7ZrNWYzxiDitub4UuAL4d2ALsKHZbQPwwIBmlNSSk2exz3JgU0SMMRWU+zLzHyJiO3BfRFwP7AOuG+CcklowYyAy8/vA2i7r/wNcPoihJI0GP0kpqWQgJJUMhKSSgZBUMhCSSgZCUslASCoZCEklAyGpZCAklQyEpJKBkFQyEJJKBkJSyUBIKhkISSUDIalkICSVDISkkoGQVDIQkkoGQlLJQEgqGQhJJQMhqWQgJJUMhKSSgZBUMhCSSgZCUslASCoZCEklAyGpZCAklQyEpJKBkFQyEJJKMwYiIlZGxLci4smI2B0RNzbrZ0TE1oh4qrk8ffDjShqm2RxBvAb8bma+F7gE+K2IOB+4GdiWmauBbc1tSYvIjIHIzEOZ+W/N9ReBJ4EVwLXApma3TcC6Ac0oqSVzeg8iIlYBa4EdwFmZeQimIgIsK+5zQ0RMRsTk4cOHexxX0jDNOhAR8TPAN4EvZOaPZ3u/zLwrMycyc2J8fHw+M0pqyawCERFLmIrDPZl5f7P8XEQsb7YvB54fzIiS2jKbsxgBfA14MjO/3LFpC7Chub4BeKD/40lq08mz2OfDwK8DuyLiiWbt94Dbgfsi4npgH3DdQCaU1JoZA5GZ3wGi2Hx5f8eRNEr8JKWkkoGQVDIQkkoGQlLJQEgqGQhJJQMhqWQgJJUMhKSSgZBUMhCSSgZCUslASCoZCEklAyGpZCAklQyEpJKBkFQyEJJKBkJSyUBIKhkISSUDIalkICSVDISkkoGQVDIQkkoGQlLJQEgqGQhJJQMhqWQgJJUMhKSSgZBUMhCSSgZCUslASCrNGIiI+OuIeD4iftCxdkZEbI2Ip5rL0wc7pqQ2zOYI4m+Aa05YuxnYlpmrgW3NbUmLzIyByMxvAy+csHwtsKm5vglY19+xJI2C+b4HcVZmHgJoLpf1byRJo2Lgb1JGxA0RMRkRk4cPHx7000nqo/kG4rmIWA7QXD5f7ZiZd2XmRGZOjI+Pz/PpJLVhvoHYAmxorm8AHujPOJJGyWxOc94LbAfWRMSBiLgeuB24MiKeAq5sbktaZE6eaYfMXF9surzPs0gaMX6SUlLJQEgqGQhJJQMhqWQgJJUMhKSSgZBUMhCSSgZCUslASCoZCEklAyGpZCAklQyEpJKBkFQyEJJKBkJSyUBIKhkISSUDIalkICSVDISkkoGQVDIQkkoGQlLJQEgqGQhJJQMhqWQgJJUMhKSSgZBUMhCSSie3PYCkN/rMV7fzyN4Xfmr9mds/NvRZDIQ0Albd/OCs9hl2JAyE1KJf3Pggr+Xs958OyVgE6y9eyZfWXTCgyab4HoTUkrnGodOxTO5+dB+3bt7V36FO4BGE1JL5xqHT3Y/uY+vu/+a5F185vnbWz76NHbdc2fuD4xGEtOB1xmH69gdu++e+PHZPgYiIayJiT0Q8HRE392UiST378cvH+MxXt/f8OPMORESMAX8BfBQ4H1gfEef3PJGkvnhk7ws9v0fRyxHERcDTmfmfmfkK8A3g2p6mkd4iZnNasx/u2bGvp/v38iblCmB/x+0DwMUn7hQRNwA3AJx77rk9PJ1U2/z4Qe54aA/PHjnK2act5aar17Bu7Yq2x+pqWHEAyB7fCO3lCCK6rP3UOJl5V2ZOZObE+Ph4D08ndbf58YNsvH8XB48cJYGDR46y8f5dbH78YNujLXi9BOIAsLLj9jnAs72NI83dHQ/t4eirx96wdvTVY9zx0J6WJqoN8+hhWi+h7CUQ3wVWR8R5EfE24NPAlh4eT5qXZ48cndN6W9qIA9BTKOcdiMx8Dfht4CHgSeC+zNw970mkeTr7tKVzWn+r6SWUPX0OIjP/MTPfk5nvzsw/7uWxpPm66eo1LF0y9oa1pUvGuOnqNS1NNFp6CaUftdaCN322YqGcxRik4I1nCnoNpYHQorBu7Yq3ZBA6nXrKGH+47oK+htJASIvAZy859/ivfvczlP6ylqSSgZAWgXt37J95p3kwENIicKzXz1QXDIS0CIxFt9986J2BkBaB9RevnHmneTAQ0pAM8hupB/XltQZCGqJnbv9Y30Px2UsG9zUKBkJawE49ZWygX31vIKQFavWyd/L9L14z0Ofwk5TSAjPMf13LIwhJJQMhqWQgpAXkHUuG+7+sgZBa8OF3nzHn+5wU8Ce/+oEBTPMmzznUZ5MEwD2fv3TOkfjypy4c+ndeeBZDask9n78UmPrW6T/YspsjR18t9z39HUta+UIcjyCklq1bu4InbrvqTY8obvv4+4Y40esMhDQiur3sWHIS/PmvDf+lxTRfYkgjZPplx6jwCEJSyUBIKhkISSUDIalkICSVIgf0bbhdnyziMPDDPj/smcCP+vyYg7bQZl5o84Izz8W7MnO824ahBmIQImIyMyfanmMuFtrMC21ecOZ+8SWGpJKBkFRaDIG4q+0B5mGhzbzQ5gVn7osF/x6EpMFZDEcQkgbEQEgqLahARMR1EbE7Iv4vIiY61q+MiJ0Rsau5vKxj24ea9acj4isRA/pXTuc2789HxLci4qWIuPOE+7Q275vN3Gzb2My1JyKuHpWZO+b4YERsb2b5+4g4dabZ2xYRF0bEoxHxRERMRsRFHdvanzkzF8wP8F5gDfAwMNGxvhY4u7n+fuBgx7bHgEuBAP4J+OgIzPtO4JeA3wTuPOE+rc07w8znA98DTgHOA/YCY6Mwc8eM3wU+0lz/DeCPZpq97R/gX6b/vIBfBh4epZkX1BFEZj6ZmXu6rD+emc82N3cDb4+IUyJiOXBqZm7PqT/1rwPrRmDen2Tmd4D/7Vxve95mtq4zA9cC38jMlzPzv4CngYtGYeYOa4BvN9e3Ap9srnedvYX5uklg+kjn54Dp/45HYuYFFYhZ+iTweGa+DKwADnRsO9CsjapRnncFsL/j9vRsozTzD4BPNNevA1Y216vZR8EXgDsiYj/wZ8DGZn0kZh65b5SKiH8FfqHLplsy84EZ7vs+4E+Bq6aXuuzW1/O6vczb7eG6rPX9PPQ8Z65mG8rMx4d4k9mZelnxlYj4fWAL8Mr03brsP7Tz+zPMfDnwO5n5zYj4FPA14ApannnayAUiM6+Yz/0i4hzg74DPZebeZvkAcE7Hbufw+iFcX8x33sLA54V5z3yA1/9GhtdnG8rM02Yx+1UAEfEeYPofsaxmH4o3mzkivg7c2Nz8W+CvmuutzjxtUbzEiIjTgAeBjZn5yPR6Zh4CXoyIS5p31j8HzPVv9aEZ8Xm3AJ9u3ts5D1gNPDZKM0fEsubyJOBW4C+bTV1nb2PGLp4FPtJcvwx4qrk+GjO3/S7uHN/x/RWmyvoy8BzwULN+K/AT4ImOn2XNtgmmXpvuBe6k+fRom/M2254BXgBeavY5v+15ZzHzLc1ce+g4U9H2zB1z3Aj8R/Nze+cc1ext/zB1NmsnU2csdgAfGqWZ/ai1pNKieIkhaTAMhKSSgZBUMhCSSgZCUslASCoZCEml/wdnaTO8dpdxrwAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Convertir la base RS2018 en formato espacial\n",
    "\n",
    "df_MIES_gdf= gpd.GeoDataFrame(df_MIES, geometry= gpd.points_from_xy(df_MIES['lon'],df_MIES['lat']))\n",
    "df_MIES_gdf['geometry'] = df_MIES_gdf['geometry'].astype(str).apply(wkt.loads)\n",
    "gdf_hog = gpd.GeoDataFrame(df_MIES_gdf)\n",
    "\n",
    "gdf_hog = gdf_hog.set_crs(\"EPSG:4326\")\n",
    "gdf_hog.plot()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Debido a que los puntos de MIES tiene puntos geográficos equivocados (puntos que se encuentran por afuera del Ecuador), se realiza los siguientes pasos:"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "1. Se carga el shape de las provincias de Ecuador y se convierte en el formato 4326 (mismo formato geográfico de la base del MIES)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 105: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 105: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 105: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 105: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 110: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 110: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 110: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 110: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 101: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 101: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 101: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 101: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 105: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 105: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 105: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 105: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 110: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 110: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 110: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 110: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 101: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 101: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 101: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 101: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\marco\\anaconda3\\envs\\geo_env\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte\n"
     ]
    }
   ],
   "source": [
    "df_prov= gpd.read_file(\"../data/Ecuador_provincias/ecuador.shp\") #Se lee la base de datos .Shp\n",
    "df_prov = df_prov.to_crs(\"EPSG:4326\")"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "2. Intercepción entre los beneficiarios del MIES y shape de las provincias de Ecuador.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>zp</th>\n",
       "      <th>ud_mies</th>\n",
       "      <th>dpa_provin</th>\n",
       "      <th>dpa_despro</th>\n",
       "      <th>dpa_cant</th>\n",
       "      <th>dpa_descan</th>\n",
       "      <th>dpa_parroq</th>\n",
       "      <th>dpa_despar</th>\n",
       "      <th>beneficio</th>\n",
       "      <th>edad</th>\n",
       "      <th>...</th>\n",
       "      <th>OBJECTID</th>\n",
       "      <th>DPA_PROVIN</th>\n",
       "      <th>DPA_DESPRO</th>\n",
       "      <th>DPA_VALOR</th>\n",
       "      <th>DPA_ANIO</th>\n",
       "      <th>REI_CODIGO</th>\n",
       "      <th>REN_CODIGO</th>\n",
       "      <th>PEE_CODIGO</th>\n",
       "      <th>Shape_Leng</th>\n",
       "      <th>Shape_Area</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Zona Planificación 6</td>\n",
       "      <td>UNIDAD DESCONCENTRADA ZONAL 6</td>\n",
       "      <td>1</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>108</td>\n",
       "      <td>SANTA ISABEL</td>\n",
       "      <td>10851</td>\n",
       "      <td>ABDON CALDERON (LA UNION)</td>\n",
       "      <td>PENSION MIS MEJORES AÑOS</td>\n",
       "      <td>73.0</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>01</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2010</td>\n",
       "      <td>05</td>\n",
       "      <td>01</td>\n",
       "      <td>593</td>\n",
       "      <td>679651.580798</td>\n",
       "      <td>8.325642e+09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Zona Planificación 6</td>\n",
       "      <td>UNIDAD DESCONCENTRADA ZONAL 6</td>\n",
       "      <td>1</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>101</td>\n",
       "      <td>CUENCA</td>\n",
       "      <td>10150</td>\n",
       "      <td>CUENCA</td>\n",
       "      <td>PENSION PARA ADULTOS MAYORES</td>\n",
       "      <td>81.0</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>01</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2010</td>\n",
       "      <td>05</td>\n",
       "      <td>01</td>\n",
       "      <td>593</td>\n",
       "      <td>679651.580798</td>\n",
       "      <td>8.325642e+09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Zona Planificación 6</td>\n",
       "      <td>UNIDAD DESCONCENTRADA ZONAL 6</td>\n",
       "      <td>1</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>101</td>\n",
       "      <td>CUENCA</td>\n",
       "      <td>10150</td>\n",
       "      <td>CUENCA</td>\n",
       "      <td>PENSION PARA ADULTOS MAYORES</td>\n",
       "      <td>81.0</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>01</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2010</td>\n",
       "      <td>05</td>\n",
       "      <td>01</td>\n",
       "      <td>593</td>\n",
       "      <td>679651.580798</td>\n",
       "      <td>8.325642e+09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Zona Planificación: Quito</td>\n",
       "      <td>UNIDAD DESCONCENTRADA DISTRITAL TIPO B QUITO C...</td>\n",
       "      <td>17</td>\n",
       "      <td>PICHINCHA</td>\n",
       "      <td>1701</td>\n",
       "      <td>DISTRITO METROPOLITANO DE QUITO</td>\n",
       "      <td>170150</td>\n",
       "      <td>QUITO</td>\n",
       "      <td>PENSION MIS MEJORES AÑOS</td>\n",
       "      <td>82.0</td>\n",
       "      <td>...</td>\n",
       "      <td>17.0</td>\n",
       "      <td>17</td>\n",
       "      <td>PICHINCHA</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2010</td>\n",
       "      <td>04</td>\n",
       "      <td>01</td>\n",
       "      <td>593</td>\n",
       "      <td>722044.248544</td>\n",
       "      <td>9.537906e+09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Zona Planificación 6</td>\n",
       "      <td>UNIDAD DESCONCENTRADA ZONAL 6</td>\n",
       "      <td>1</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>101</td>\n",
       "      <td>CUENCA</td>\n",
       "      <td>10112</td>\n",
       "      <td>SUCRE</td>\n",
       "      <td>BONO JOAQUIN GALLEGOS LARA</td>\n",
       "      <td>86.0</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>01</td>\n",
       "      <td>AZUAY</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2010</td>\n",
       "      <td>05</td>\n",
       "      <td>01</td>\n",
       "      <td>593</td>\n",
       "      <td>679651.580798</td>\n",
       "      <td>8.325642e+09</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 25 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                          zp  \\\n",
       "0       Zona Planificación 6   \n",
       "1       Zona Planificación 6   \n",
       "2       Zona Planificación 6   \n",
       "3  Zona Planificación: Quito   \n",
       "4       Zona Planificación 6   \n",
       "\n",
       "                                             ud_mies dpa_provin dpa_despro  \\\n",
       "0                      UNIDAD DESCONCENTRADA ZONAL 6          1      AZUAY   \n",
       "1                      UNIDAD DESCONCENTRADA ZONAL 6          1      AZUAY   \n",
       "2                      UNIDAD DESCONCENTRADA ZONAL 6          1      AZUAY   \n",
       "3  UNIDAD DESCONCENTRADA DISTRITAL TIPO B QUITO C...         17  PICHINCHA   \n",
       "4                      UNIDAD DESCONCENTRADA ZONAL 6          1      AZUAY   \n",
       "\n",
       "   dpa_cant                       dpa_descan  dpa_parroq  \\\n",
       "0       108                     SANTA ISABEL       10851   \n",
       "1       101                           CUENCA       10150   \n",
       "2       101                           CUENCA       10150   \n",
       "3      1701  DISTRITO METROPOLITANO DE QUITO      170150   \n",
       "4       101                           CUENCA       10112   \n",
       "\n",
       "                  dpa_despar                     beneficio  edad  ...  \\\n",
       "0  ABDON CALDERON (LA UNION)      PENSION MIS MEJORES AÑOS  73.0  ...   \n",
       "1                     CUENCA  PENSION PARA ADULTOS MAYORES  81.0  ...   \n",
       "2                     CUENCA  PENSION PARA ADULTOS MAYORES  81.0  ...   \n",
       "3                      QUITO      PENSION MIS MEJORES AÑOS  82.0  ...   \n",
       "4                      SUCRE    BONO JOAQUIN GALLEGOS LARA  86.0  ...   \n",
       "\n",
       "   OBJECTID  DPA_PROVIN DPA_DESPRO DPA_VALOR  DPA_ANIO  REI_CODIGO REN_CODIGO  \\\n",
       "0       1.0          01      AZUAY       0.0      2010          05         01   \n",
       "1       1.0          01      AZUAY       0.0      2010          05         01   \n",
       "2       1.0          01      AZUAY       0.0      2010          05         01   \n",
       "3      17.0          17  PICHINCHA       0.0      2010          04         01   \n",
       "4       1.0          01      AZUAY       0.0      2010          05         01   \n",
       "\n",
       "  PEE_CODIGO     Shape_Leng    Shape_Area  \n",
       "0        593  679651.580798  8.325642e+09  \n",
       "1        593  679651.580798  8.325642e+09  \n",
       "2        593  679651.580798  8.325642e+09  \n",
       "3        593  722044.248544  9.537906e+09  \n",
       "4        593  679651.580798  8.325642e+09  \n",
       "\n",
       "[5 rows x 25 columns]"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_final = gpd.sjoin(gdf_hog,df_prov,how='left')\n",
    "df_final.head(2)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "3. Se elimina los puntos que están afuera de Ecuador"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<AxesSubplot:>"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXIAAACrCAYAAAB7YhdaAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAWqklEQVR4nO3df5DcdX3H8ec7lwM2qfagBDULMYgxrRjITa8EmjpWNASJ4hmEiNB2SgfaGZkWHK+SJgoINKlRTFudccJUbYcUIwoLNh2PIHV0GIJeekmOKBHQGFhaiIWIwkkul3f/2N1zb2/3dm/3u99f+3rMZLL73b3v982F73s/+/78MndHRESSa1bUAYiISGuUyEVEEk6JXEQk4ZTIRUQSTolcRCThZkdx0ZNPPtkXLlwYxaVFRBJr165dP3f3eZXHI0nkCxcuZGhoKIpLi4gklpn9rNpxlVZERBJOiVxEJOEiKa2ISHrlhvNsGtxP/vDolNcObFwVQUTppxa5iARmfW6E67ftrprEARbesD3kiDqDErmItCw3nKf3Uw9w586D1Fu96awbvxVKTJ1EiVxEWlJqhb/4ylhD73/p1XFyw/k2R9VZVCMXkbpyw3mu27Y7sPMN3L2b/t5sYOfrdGqRi8i01udGAk3iAGPHUKs8QIG0yM3sS8B7gefd/W1BnFNEohNGp+Smwf1qlQckqNLKV4DPA/8W0PlEJCJhjSx5tsrIltLQxWcPjzK/J8PAysVK9g0IJJG7+3fNbGEQ5xKR8EUxLHB+T2bS89xwnrX3jDA6Ng5A/vAoa+8ZAVAyryO0zk4zuwa4BmDBggVhXVZEqphu0k4YMt1dDKxcPOnYpsH9E0m8ZHRsfEoJRq32qUJL5O6+BdgC0NfXp41CRSKy4vbv8MTzL0caw4bVS+jvzU5KyrWSQnkJJjecZ+DuPYwdK7w7f3iUgbv3AJ3dateoFZEOcsUdj0SexLM9mYkkvvaeEfLTJHGYXIK56f59E0m8ZOyYc9P9+9oUbTIokYt0kIefeiHS65eXVKqVUip1d9mkEszh0eqTjmod7xSBJHIzuwt4BFhsZs+Y2V8EcV4RSY+eTPdESQWqj1qpNDbuDP0s2g+fJAhq1MrlQZxHRNLnxDnd3Pi+M6fUsOf3ZBrqbL1z50Hu3HmQ7jrNztxwvmPr5CqtiEhb9GS62bxmKcOfvKBqgh1YuZhMd1fD5xs7Nv3rmwb3zzTE1NBaKyISuOVnnMTWq8+b9j2l5F4aBmlQd+XE6TRSqkkrJXIRCdzDT73A+twIt/YvmfZ9/b3ZiYTe6sJclROMgrY+N8Jdjz7NuDtdZly+7LS6/31hUWlFpIMsOmVuaNe669GnQ7vWLGPKBKMgrc+NcOfOg4x74TvDuDt37jzI+txI2645E2qRi3SQHR/949Cm45eSXnlLtiRbZUbmunubS4pdBp+9bGlbOzprfSjd9ejTsWiVK5GLSNucdeO3eOnVqWPFq62j8vKR6ceUV9NILb5cs9P7yz+EGjkeNiVyEWmbakm8ZHRsnLX37KW/N8sVdzwy43OfOKd7xkm8clGu67btrlqXb7XjNWxK5CISmdGxY02v/XK4wa3l1udG2NrAXqLlkpTEQYlcRCLW7Nov1ZbBLQ1l7DJj3J3uWfXHn7dq2W07eHTdivZepA4lchFJnMplcCvLJqXadbuTOMBzvzzCm9Zuxx0y3bMYPXoMd0IdoqhELiKJ0pPp5qaLJ0/5b2QBrnYqLcj4StknR2mIItD2ZB7UolkXmtl+M3vSzG4I4pwiErwodgIKSrYnw+Y1S9l949Qp/3Ge1RnGePqWW+Rm1gV8AVgBPAP8wMzud/cftnpuEZGSh284v+ZrPXO6ebHBzs+whTFEMYgW+TnAk+7+E3c/AnwVeH8A5xWRACW5NV7Pr34dzyQOhVp5uwVRI88C5d8dngGWVb5Je3aKRCdNSbzapJ4wOjWbdfmy09p+jSBa5NU+bqZ8l3D3Le7e5+598+bNC+CyItKItCXx8u3hymeIxsGc7lmUGuBdZlx57oLEjFp5Bij/yDkVeDaA84pIi9KSxEutxWqjU6IcrVLph7e8J5LrBpHIfwAsMrPTgTzwIeDDAZxXRFqQliQO8NONq4B4j04BWL7xoRmv4xKElksr7n4UuBYYBH4EfM3dO3tLa5GIpSWJZ7q72LxmKVCYal9r/Ee2J8OV5y6Y6FjsMgt1yV4ofGuoLPnkhvPhXNsjWL2rr6/Ph4aGQr+uSCdISxIH2LymsDxtaT3weu+rVO/ngjJ7lnH02NRcmu3JTDtscqbMbJe791Ue18YSIhJLBzaumkjO9SbV1Cph3Nq/pOpojCBdee4CxqskcQivFKRELpIib16bntZ4uVYm1fTM6Q4wkslKo1JqbTPX7u3nSrTWikiKHE3a+qs1HCh2bpaUVjNsRG44z83f3Nf2mZ7lQwsHVi6etGgXTF3Yq53UIheRWHnt8V1Tjk03qWb5GSdNPC5t4BxmEodCaWfD6iVkezIYhdr4htVLQhu1oha5iMTK3psvnHKslDQrOy4rt3qrtttP0LI9maqTfPp7s6El7kqJSeTN7rUnIslRGmpYza39S+h740mT8sDp835r0tjtIL3uNcfx3C+PTDoWZrlkJhKRyKvttVe5cauIJFe2gcZZtTxQ3kLPBzxC5NF1KxLTgExEIq81LXfT4P5Y/lJFZGYaGWsd9uYRueF8oOWSdn4oJKKzs9ZYzLhP1xUJU1InAjU6zjvs+33T4P7AzlVrsa+gZn4mIpFHPUZTRNpnznFTR6lUE/b9HuQHx3RVhSAkIpEPrFxMpnvyP3ZcOx1EZGZePlK/XLI+NxJ4DbyeID842l1VSESNvFRHSkKng0i7JbWE0qyw1kspZxBoQ3F+T6bqB1FQHxYtJXIzuxS4Cfg94Bx3b9tKWFGO0RSJi7Qm8VLHYjVhbF5c6YpzFwSab9o987PV0spjwGrguwHEIiIdat29tXf5CWPz4nLt2NWn3TM/W2qRu/uPACyEzUVFOl1aW+NQqJOvz42Esi3adGothxuEdlYVQuvsNLNrzGzIzIYOHToU1mVFJCGiKKFUSmr5tm6L3MweBF5f5aV17n5foxdy9y3AFihsLNFwhCLSEcIuoVTqSnBloW4id/d3hxGIiHS2diTSWcDtFeWSWqNgplthMe4SMfxQRNLvTfPmTDnWyszHWvXuUh3+rkefZtydLjMuX3Za5PX5VrQ6/PADwD8D84DtZrbb3VcGEpmIdJQnD7086fkVdzzCw0+90NS5Fp0yd9p69639SxKduCu11Nnp7ve6+6nufry7v05JXKR9KnfNSRv337TA1+dGmk7iy884iR0f/eMAI4u/REzRF5GCtCfzgbt3A82PYDGYtNFEp1AiF0mY6TZfSLqxY4W/mx3BMssssBUFk0SJXCRhkjrWuVFX3PFI0z877h7o8rBJoUQukjBpnuEJNF0bLwlyedikUCIXSZC0J/HlZ5wUyHk6bdMZJXIRiYXlZ5wUWEdlp206o0QuIrFQSuKttsqDXks8CZTIRSRy5cl769XnseiUuU2fy0l/h3AlJXIRiVxlSeWVI8eaPle2w8oqoEQukihpnxBU0mxnZafu5atFs0QkdswKU/ZnItvBe/m2umjWJuB9wBHgKeDP3f1wAHGJSA0HNq5K1TDEynr4stt2cGyGSbxTvqnU0mppZQfwNnc/C/gxsLb1kESkU8w2pixw9dwvj8z4PMs3PsTpN2xn+caHOm5WJ7S++uED7n60+HQncGrrIYlIJ1h0ylye3BBMSzp/eBQv/t2JU/SDrJFfBWyr9aKZXQNcA7BgwYIALysiSVOrFLI+N9LyuUtT9DupVl63RW5mD5rZY1X+vL/sPeuAo8DWWudx9y3u3ufuffPmzQsmepEOFESyi6ugNmDOHx7tqFJLy3t2mtmfAe8F3uUe8e6pIimWpg7O3HC+aos5yA2Yy0stkO5JQi3VyM3sQuDjwMXu/kowIYlIpTQlcaDq6oStLF87ndGxcdbdm95vMdD6qJXPA68BdpjZbjP7YgAxiUjK5Q+PTil5tLp87XRePjKe6pJUq6NW3uzup7n70uKfvwoqMBFJt7BHlwRVf48jTdEXkUi0ugFEd5fRPcsafn+Q9fe40RR9EYlMs2uqlKbjA1y3bXdDP9NljSf9pFGLXCQB0joFvbQBRKP1655M98Tm09dv2z2jFv3ly06bcXxJoRa5iETm6Pg4AFt3Hmzo/e89+w2svWeE0bHCz+UbbNFfee4Cbu1f0lyQCWBRDP3u6+vzoaGh0K8rknRBD0Os3F5t2W07mlrrJCzZnkzDybuky4ynNlzUpojCZWa73L2v8rha5CIJUlliaSWxm03d0GHtRW9tuOYctmxPpqmaeppLKiWqkYsk2IGNqzihq7lOvCuWFdY8yg3nWb7xIRbesD22SRwK+3A2s6ly3xtb2wM0CZTIRRLu8dsu4sDGVTPe4uzOnQfJDedZe8/IjMsVUejvzfLO3535Ok2tDHFMCiVykZQYWLmYGQyrBuDmb+6b6DiMs+VnnERuOM83ds18AlGzQxyTRIlcJCX6e7PcftlSjptBqeXFV8baGFFwtl59HpsG9zf1odNMOSZplMhFUqS/N8uPb7uI5Wekpy5c2gqumZZ1p2zGrEQukkJbrz4vNcm8tBVcMy3rDauXpHr52pJWl7G9xcz2Flc+fMDM5gcVmIi0ZuvV503Mgkyqnkz3xOPS5KFGXXnugo5I4tDihCAze627v1R8/NfAWxtZAVETgkTCVxqhUl5nznR3JaKzc6YqJzqlRa0JQa0uY/tS2dO5FDblEJEY6u/NsmH1ErI9GYzCBJsNq9M3bf2ELktlEp9OyzM7zew24E+BXwDvnOZ92nxZJGL9vdlJ5YYVt38numDa4LXHd7H35gujDiN0dUsrZvYg8PoqL61z9/vK3rcWOMHdb6x3UZVWROIhLVvIbV6ztCPq4U2vtVJv8+Uy/w5sB+omchGJVm44H+vp+I2aPcv4zKVnd0QSn05LpRUzW+TuTxSfXgw83npIItJOSU/ii06ZOzEkUQpaHUe+0cweM7O9wAXA3wQQk4i0URLWHjmwcRWb1yylcpKqknh1LbXI3f2SoAIRkXDEfe2R0mqOlR2zUpvWIxfpAEnq1Hz8tnRsAhEmTdEXSbkkJfGkz0SNihK5iMSGSinNUSIXEUk4JXIRkYRTIhcRSTglchGRhFMiF0m5AxtXRR1CQ06YwRZ1MpkSuUgHKN+gIY4MjR9vhRK5SAe46eIz6Z4V3xbvTxPyrSGuNLNTpAOUxmfHcbGspJR+4iyQFrmZfczM3MxODuJ8IhI8TbZJryB2CDoNWAEcbD0cEQlSbjjPTffv4/DoWNShSBsF0SL/HPC3aL9OkVjJDecZuHtP7JN4bjgfdQiJ11IiN7OLgby772ngvdeY2ZCZDR06dKiVy4pIAzYN7mfsWPzbV0lYHz3u6pZWptuzE/g7ChtK1OXuW4AtUNizcwYxikgT8jFfd7wk7uujJ0HTe3aa2RLgdGCPmQGcCvy3mZ3j7v8baJQiMiO54TxGMuqd83syUYeQeE13drr7CHBK6bmZHQD63P3nAcQlIi3YNLg/EUk8093FwMrFUYeReJoQJJJCSShX9GS62bB6iYZFBiCwRO7uC9UaF4mHuJcruruMmy4+U0k8IJrZKZJCAysXc/223ZGUVypnai7f+NCUjtexcWfT4H4l8oCotCKSQv292djUyGuVeZJQ/kkKJXKRlMpGUF6pds1aZZ64l3+SRIlcJKUGVi4m091V9bXuNqz9Pat4zUbi0GiVYCmRi6RUf2+WDauXTLSSuwrzPcj2ZNj0wbMDvVamexa3r1lateZdHocVr6/RKsEy9/AraX19fT40NBT6dUVksoU3bG/5HJvXLGXT4H7yh0fpMmPcnWxPhoGVi5WsA2Zmu9y9b8pxJXIRKS2w1czaLJnuLkbHxqseV8s7WLUSuUorIkJ/b5ZNl549aUu4E+d0M/e46jX2ctWSeOm4FsQKh8aRiwhQSOaVrefccJ6Br+9hbLy5b+4aYhgOtchFpKb+3iybPnh21Zb5LOpv6qwhhuFQIheRafX3Ztn3qQvZvGbppJEnt69ZyrzXHFfz5zTEMDwqrYhIQypLL7nhPE88/3LN91/y+1NLNdIere4QdJOZ5c1sd/HPRUEFJiLxVq8j878e105gYQmiRf45d/9MAOcRkQSp15Gpjs7wqEYuIk2p15Gpjs7wBJHIrzWzvWb2JTM7sdabtPmySLpMt5aLOjrDVXdmZ53Nl3cCP6ewNeAtwBvc/ap6F9XMTpF0yA3nNT0/RLVmdja9+XKVC9wB/EcTsYlIQlWbRCTha3XUyhvKnn4AeKy1cEREZKZaHbXyaTNbSqG0cgD4y1YDEhGRmYlk9UMzOwT8rE2nP5lC3T7OFGMwFGMwFGMwwojxje4+r/JgJIm8ncxsqFpnQJwoxmAoxmAoxmBEGaPGkYuIJJwSuYhIwqUxkW+JOoAGKMZgKMZgKMZgRBZj6mrkIiKdJo0tchGRjqJELiKScKlI5GZ2tpk9YmYjZvZNM3tt2WtrzexJM9tvZisjjHGpme0srts+ZGbnFI93m9m/FmP/kZmtjVuMxdfOKv6O9xVjPSFuMRZfX2BmvzKzj0UR33QxmtkKM9tV/P3tMrPz4xZj8bW43DPbyvY6OGBmu4vH43TPVI2x+Fp494y7J/4P8APgHcXHVwG3FB+/FdgDHA+cDjwFdEUU4wPAe4qPLwK+U3z8YeCrxcdzKMyQXRizGGcDe4Gzi89/J26/x7LXvwHcDXwsivjq/B57gfnFx28D8jGMMTb3TEW8nwU+WXwcm3tmmhhDvWdS0SIHFgPfLT7eAVxSfPx+Cv/gr7r7T4EngXOq/HwYHCh9U/ht4Nmy43PNbDaQAY4AL4Uf3kQs1WK8ANjr7nsA3P3/3H08gvigdoyYWT/wE2Bf+GFNUjVGdx9291K8+4ATzOz4COKD2r/HON0zAJiZAZcBdxUPxemeAarGGOo9k5Y9Ox8DLgbuAy4FTisez1JYarfkmeKxKFwHDJrZZyiUtP6wePzrFG6e/6HQurje3V+IJMLaMb4FcDMbBOZRuNE/HU2I1WM0s7nAx4EVQGRllaLrqP57LHcJMOzur4YZWJnrqB5jnO6ZkrcDz7n7E8XncbpnSipjDPWeSUwir7Mu+lXAP5nZJ4H7KXxCA1iV97dtvGWdGN9F4X+4b5jZZcC/AO+m0NoZB+YDJwLfM7MH3f0nMYpxNvBHwB8ArwDfLq6L/O0YxXgzhW0Hf1VoHLVXkzGWfvZM4B8otNriFmNs7hl3v6/4+HJ+09KFGN0z08QY6j0TaU2pTXWqtwDfLz5eC6wte20QOC+iuH7Bb8btG/BS8fEXgD8pe9+XgMtiFuOHgK+Uve8TwEDMYvwehVrpAeAw8AJwbZxiLD4/FfgxsDyK2Br4PcbmnilefzbwHHBq2bHY3DPTxBjqPZOKGrmZnVL8exawHvhi8aX7gQ+Z2fFmdjqwCPh+NFHyLPCO4uPzgdJXsIPA+VYwFzgXeDyC+KB2jIPAWWY2p1iXfAfwwwjigxoxuvvb3X2huy8ENgN/7+6fjyTCGjGaWQ+wnUKifDia0CbU+reO0z0DhW8Jj7v7M2XH4nTPQPUYQ71nElNaqeNyM/tI8fE9wJcB3H2fmX2Nwi/wKPARj66T7mrgH4v/qL8Grike/wKFeB+j0DL6srvvjSbE6jG6+4tmdjuF0UEO/Ke7b49TjDFTK8ZrgTcDnzCzTxSPXeDuz8clxpjdM1Bo2d5VcSxO9wxUiTHse0ZT9EVEEi4VpRURkU6mRC4iknBK5CIiCadELiKScErkIiIJp0QuIpJwSuQiIgn3/4IfHS30PQ0DAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "df_final.dropna(subset=['DPA_DESPRO'], inplace = True )\n",
    "df_final.plot()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "geo_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.2"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "dc6c5260799e5b2685952dc67c6d27d3ce639d6d7da909a7a1e0f625b83bdacd"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
